### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mountnside** [mountnside/mupen64plus-video-parallel#1]
- [x] Add upscaling, including supersampled dither
- [x] Add fullscreen toggle
- [x] Add configuration parsing
- [x] Add missing options from parallel libretro impl. (vi divot,etc)

`
